src/Entity/Panier.php
<?php

namespace App\Entity;

use App\Repository\PanierRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: PanierRepository::class)]
class Panier
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\Column(type: 'decimal', precision: 10, scale: 2, nullable: true)]
    private $prix_total;

    #[ORM\OneToOne(targetEntity: User::class, cascade: ['persist', 'remove'])]
    private $user;

    #[ORM\OneToMany(mappedBy: 'panier', targetEntity: Voiture::class)]
    private $voiture;

    public function __construct()
    {
        $this->voiture = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getPrixTotal(): ?string
    {
        return $this->prix_total;
    }

    public function setPrixTotal(?string $prix_total): self
    {
        $this->prix_total = $prix_total;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

    /**
     * @return Collection<int, Voiture>
     */
    public function getVoiture(): Collection
    {
        return $this->voiture;
    }

    public function addVoiture(Voiture $voiture): self
    {
        if (!$this->voiture->contains($voiture)) {
            $this->voiture[] = $voiture;
            $voiture->setPanier($this);
        }

        return $this;
    }

    public function removeVoiture(Voiture $voiture): self
    {
        if ($this->voiture->removeElement($voiture)) {
            // set the owning side to null (unless already changed)
            if ($voiture->getPanier() === $this) {
                $voiture->setPanier(null);
            }
        }

        return $this;
    }
}

src/Controller/PanierController.php
<?php

namespace App\Controller;

use App\Entity\Panier;
use App\Repository\UserRepository;
use App\Repository\PanierRepository;
use App\Repository\VoitureRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

class PanierController extends AbstractController
{
    #[Route('/accueil/panier', name: 'panier')]
    // On passe en paramètre de notre méthode les classeRepository dt on va av besoin pr questionner la BDD,
    // la classe request de symfony pr récupérer certaines choses (dont l'url) et la classe EntityManagerInterface
    // pour enregistrer en BDD
    public function listeChoixPanier(PanierRepository $repo1, VoitureRepository $repo2, UserRepository $repo3, Request $req, EntityManagerInterface $em): Response
    {
        // Notre logique de fonctionnement du panier
        // 1 - Voir si un panier existe pour le user connecté
        // Récupération de la personne connectée avec cette ligne spécifique à symfony
        $user = $this->getUser();
        // Récupération du panier lié à ce user
        $panier = $repo1->findOneBy(['user' => $user], ['id' => 'DESC']);
        
        // Récupération de l'id du choix de la voiture 
        $idVoitureChoix = $req->get('id');
        // dd($idVoitureChoix);
        // Si le panier est vide et que l'on a cliqué sur ajouter au panier
        if(($panier == null) && ($idVoitureChoix !== null)):
            // récupération des informations de la voiture choisie par rapport à l'id
            $infoVoitureChoix = $repo2->findOneById($idVoitureChoix);
            //dd($infoVoitureChoix);
            // On créer un nouveau panier
            $panier = new Panier;
            $panier->addVoiture($infoVoitureChoix);
            // dd($panier);
            // Mettre à jour le panier aux infos de l'utilisateur connecté
            $panier->setUser($user);
            // Faire disparaître la voiture en Front car elle est ds un panier
            $infoVoitureChoix->setActive(false);
            // Ancienne méthode d'enregistrement en BDD (si non c'est avec add)
            $em->persist($panier);
            $em->flush();
        elseif(($panier !== null) && ($idVoitureChoix !== null)):
                // le panier existe et une voiture est selctionnée
                // récupération des informations de la voiture choisie par rapport à l'id
            $infoVoitureChoix = $repo2->findOneById($idVoitureChoix);
            $panier->addVoiture($infoVoitureChoix);
            // dd($panier);
            // Mettre à jour le panier aux infos de l'utilisateur connecté
            $panier->setUser($user);
            // Faire disparaître la voiture en Front car elle est ds un panier
            $infoVoitureChoix->setActive(false);

            // Calcul du prix total
            // Récupérer le panier complet du user
            $PanierListeChoixVoiture = $repo1->findOneBy(['user' => $user]);
            // Récupération de la liste des voitures du user
            $listeChoixVoiture = $panier->getVoiture($PanierListeChoixVoiture);
            // Passage en revue des prix des véhicules
            $tableauPrixTotal=[];
            foreach($listeChoixVoiture as $key => $voiture):
                // Récupération du prix de la voiture en cours ds la boucle
                $prixVoiture = $voiture->getPrix();
                // array_push(tableau vide ci-dessus, on ajoute le prix en cours de la voiture)
                array_push($tableauPrixTotal, $prixVoiture);
            endforeach;
            // On fait la somme de tous les éléments du tableau $tableauPrixTotal
            $totalPrix = array_sum($tableauPrixTotal);
            // Nous préparons la variable $totalPrix ds le champ total_prix de la BDD
            $panier->setPrixTotal($totalPrix / 100);

            // Ancienne méthode d'enregistrement en BDD (si non c'est avec add)
            $em->persist($panier);
            $em->flush();
        endif;
        //-------------GESTION PANIER VIDE ou TOTAL PRIX DU PANIER = 0.00---------------
        // Si le panier est vide, dc null rediriger l'utilisateur vers une page qui dit que le panier est vide
        // Récupération de la liste de voiture du user
        $PanierListeChoixVoiture = $repo1->findOneBy(['user' => $user]);
        $panier->getVoiture($PanierListeChoixVoiture);
        if($panier == null || $panier->getPrixTotal() == 0.00):
             return $this->redirectToRoute('panierVide');
        endif;

        // Retour rendu vers la vue templates/panier/panier.html.twig
        return $this->render('panier/panier.html.twig', [
            // 'user' => $user,
            'panier' => $panier,
            // 'request' => $req
        ]);  
    }

    #[Route('/accueil/panierVide', name: 'panierVide')]
    public function panierVide(): Response
    {
        return $this->render('panier/panierVide.html.twig', [
            
        ]);
    }
    #[Route('/accueil/supprimerVoiturePanier', name: 'supprimerVoiturePanier')]
    public function supprimerUneVoitureDuPanier(PanierRepository $repo1, VoitureRepository $repo2, EntityManagerInterface $em, Request $req)
    {
        // Récupération de la personne connectée avec cette ligne spécifique à symfony
        $user = $this->getUser();
        // Récupération du panier lié à ce user
        $panier = $repo1->findOneBy(['user' => $user], ['id' => 'DESC']);
        // Récupération de l'id voiture à supprimer
        $idVoitureChoixSupprimer = $req->get('id');
        // Récupération de toutes les infos de la voiture
        $infoVoitureChoixSupprimer = $repo2->findOneById($idVoitureChoixSupprimer);
        // Supression de la voiture sélectionnée
        $panier->removeVoiture($infoVoitureChoixSupprimer);
        // Faire réapparaître cette voiture en front
        $infoVoitureChoixSupprimer->setActive(true);

        // Recalcul du prix
        // Récupérer le panier complet du user
        $PanierListeChoixVoiture = $repo1->findOneBy(['user' => $user]);
        // Récupération de la liste des voitures du user
        $listeChoixVoiture = $panier->getVoiture($PanierListeChoixVoiture);
        // Passage en revue des prix des véhicules
        $tableauPrixTotal=[];
        foreach($listeChoixVoiture as $key => $voiture):
            // Récupération du prix de la voiture en cours ds la boucle
            $prixVoiture = $voiture->getPrix();
            // array_push(tableau vide ci-dessus, on ajoute le prix en cours de la voiture)
            array_push($tableauPrixTotal, $prixVoiture);
        endforeach;
        // On fait la somme de tous les éléments du tableau $tableauPrixTotal
        $totalPrix = array_sum($tableauPrixTotal);
        // Nous préparons la variable $totalPrix ds le champ total_prix de la BDD
        $panier->setPrixTotal($totalPrix);

        $em->persist($panier);
        $em->flush();
        // Si le sys voit la variable $totalPrix = 0 type float on redirige vers la page panierVide
        if($totalPrix == 0.00):
            return $this->redirectToRoute('panierVide');
        endif;
        return $this->redirectToRoute('panier');
    }
}

templates/panier/panier.html.twig
{% extends 'base.html.twig' %}

{% block title 'Votre panier' %}

{% block body %}
{# {{ dump (user) }} #}
{# {{ dump (panier) }} #}
{# {{ dump (request) }} #}
<div class="container">
    <div class="row text-center mt-5">
        <hr class="pt-1 mt5">
        <h2>Votre panier</h2>
        <hr class="pt-1 mt5">
        <div class="row mt-5">
            <table class="table table-light">
                <thead class="thead-light">
                    <tr>
                        <th>Nom</th>
                        <th>Marque</th>
                        <th>Couleur</th>
                        <th>Prix</th>
                        <th>Supprimer du panier</th>
                    </tr>
                </thead>

                <tbody>
                    {% for voiture in panier.voiture %}
                    <tr>
                        <td>{{ voiture.nom }}</td>
                        <td>{{ voiture.marque }}</td>
                        <td>{{ voiture.couleur }}</td>
                        <td>{{ (voiture.prix / 100)|number_format(2, ',', '') }}</td>
                        <td><a href="{{ path ('supprimerVoiturePanier', { id: voiture.id }) }}" type="button" class="btn bg-warning text-dark fw-bold">Supprimer</a></td>
                    </tr>
                    {% endfor %}
                </tbody>
                <tfoot>
                    <tr>
                        <th></th>
                        <th></th>
                        <th>Prix total :</th>
                        <th> {{ panier.prixTotal|number_format(2, ',', '') }}&ensp;€</th>
                        <th></th>
                    </tr>
                </tfoot>
            </table>
        </div>
        <div class="" pt-3>
            <a href="{{ path ('pageAccueil') }}" class="btn bg-primary text-white fw-bold">Retour</a>
        </div>
        <hr class="w-50 pt-1 mt-5">
    </div>
</div>
{% endblock %}

templates/panier/panierVide.html.twig
{% extends 'base.html.twig' %}

{% block title 'Panier vide' %}

{% block body %}
    <div class="container">
        <div class="row">
            <hr class="pt-1 mt-5">
            <h3>Votre panier est vide, veuillez ajouter une voiture</h3>
            <a href="{{ path('pageAccueil') }}" type="button" class="btn bg-primary text-light fw-bold">Revenir à la liste des voitures</a>    
            <hr class="pt-1 mt-3">
        </div>
    </div>
{% endblock %}